# Generated by Django 4.1.1 on 2022-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
