# Generated by Django 3.2.16 on 2022-11-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='question2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='question3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True),
        ),
    ]
