# Generated by Django 4.1.1 on 2022-10-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.TextField(max_length=3),
        ),
    ]
