# Generated by Django 4.1.1 on 2022-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(max_length=3),
        ),
    ]
