# Generated by Django 3.2.16 on 2022-10-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='angry',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='anxious',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='happy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hurt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='keyword',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='startled',
            field=models.IntegerField(null=True),
        ),
    ]
